Orders API Integration
razorpay/razorpay-cscart pull request #3
Opened 2017-02-22 12:51 UTC by riagarg5

2017-02-27 05:04 UTC, 73sl4 commented on app/payments/RazorpayPayment.php
> +    public function setSessionValues(array $sessionValues)
remove typehinting.

2017-02-27 13:17 UTC, 73sl4 commented on app/payments/RazorpayPayment.php
> +        $data['payment_capture'] = 1;
why not assign it while initializing `$data`?

2017-02-27 13:17 UTC, 73sl4 commented on app/payments/RazorpayPayment.php
> +        if(!empty($razorpaySignature) and !empty($razorpayPaymentId))
space after if

2017-02-27 13:17 UTC, 73sl4 commented on app/payments/RazorpayPayment.php
> +                if (hash_equals($signature , $razorpaySignature))
add a fallback for `hash_equals`?

2017-02-27 13:18 UTC, 73sl4 commented on app/payments/RazorpayPayment.php
> +                $payment = $api->payment->fetch($razorpayPaymentId);
Why are we fetching the payment here?

2017-02-27 13:18 UTC, 73sl4 commented on app/payments/RazorpayPayment.php
> +                $pp_response['transaction_id'] = @$order;
Why are we using `@`?

2017-02-27 13:19 UTC, 73sl4 commented on app/payments/RazorpayPayment.php
> +            if($success === true)
space after if

2017-02-27 13:20 UTC, 73sl4 commented on app/payments/razorpay.php
> +    $api = new Api($processor_data['processor_params']['key_id'], $processor_data['processor_params']['key_secret']);
assign key_id and key_secret to variables and use them.

2017-02-27 20:40 UTC, mayankamencherla requested changes

2017-02-27 20:40 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +                if (hash_equals($signature , $razorpaySignature))
@riagarg5 Please look at Utility library of the new php sdk

2017-02-27 20:40 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +        if(!empty($razorpaySignature) and !empty($razorpayPaymentId))
@riagarg5 Please use 
```
if((empty($razorpaySignature) === false) and 
   (empty($razorpayPaymentId) === false))
```

2017-02-27 20:40 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +                $api = new Api($keyId, $keySecret);
This is not needed. Please refactor code.

2017-02-27 20:40 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +                    $success = true;
There is no need for the if else block here. `hash_equals` returns a boolean. Please refactor.

2017-02-27 20:40 UTC, mayankamencherla commented on app/payments/razorpay.php
> +        'merchant_order_id' => $order_id
why are you setting `merchant_order_id` as a session variable? This is not needed. Just send it as a post parameter from the html form.

2017-03-01 13:34 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                    $success = true;
This is needed as in else block we need to set the error

2017-03-01 16:02 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +                    $success = true;
Initialize the error and remove the if else block.

2017-03-01 16:05 UTC, mayankamencherla commented
@riagarg5 Please go through each and every comment from each and every reviewer and respond to them. If you disagree, please state your point of view. If you agree, just respond with added or done. Please do this with all PR's.

2017-03-02 07:30 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +    public function setSessionValues(array $sessionValues)
done

2017-03-02 07:30 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +        $data['payment_capture'] = 1;
done

2017-03-02 07:31 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +        if(!empty($razorpaySignature) and !empty($razorpayPaymentId))
done

2017-03-02 07:31 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                if (hash_equals($signature , $razorpaySignature))
done

2017-03-02 07:31 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                $payment = $api->payment->fetch($razorpayPaymentId);
removed

2017-03-02 07:31 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                $pp_response['transaction_id'] = @$order;
removed

2017-03-02 07:31 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +            if($success === true)
done

2017-03-02 07:31 UTC, riagarg5 commented on app/payments/razorpay.php
> +    $api = new Api($processor_data['processor_params']['key_id'], $processor_data['processor_params']['key_secret']);
done

2017-03-02 07:31 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                $api = new Api($keyId, $keySecret);
done

2017-03-02 07:31 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                    $success = true;
done

2017-03-02 07:44 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +                    $success = (new Utility())->verifyPaymentSignature($attributes);
`$api->utility->verifyPaymentSigature`

2017-03-02 07:44 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +use Razorpay\Api\Utility;
Remove

2017-03-02 07:44 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +                catch (Errors\BadRequestError $e)
`catch(Exception $e)`

2017-03-02 07:44 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +use Razorpay\Api\Errors;
remove

2017-03-02 07:50 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                catch (Errors\BadRequestError $e)
\Exception

2017-03-02 08:03 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +                catch (Errors\BadRequestError $e)
@riagarg5 No difference.

2017-03-02 08:05 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                    $success = (new Utility())->verifyPaymentSignature($attributes);
done

2017-03-02 08:06 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +use Razorpay\Api\Errors;
done

2017-03-02 08:06 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +use Razorpay\Api\Utility;
done

2017-03-02 08:08 UTC, mayankamencherla requested changes
@riagarg5 Please respond to every comment and fix all the issues. Review your entire PR yourself and let me know when the code is ready for final review.

2017-03-02 08:08 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +
extra linebreak. Remove

2017-03-02 08:08 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +
extra linebreak. Remove.

2017-03-02 08:08 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +
extra line break. Remove.

2017-03-02 08:08 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +        return $html;
Add a line break between EOT and return $html

2017-03-02 08:59 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +        return $html;
done

2017-03-02 08:59 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +
done

2017-03-02 08:59 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +
done

2017-03-02 08:59 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +
done

2017-03-02 09:21 UTC, mayankamencherla requested changes
@riagarg5 Just add a line break between use and include. Demo the working code to me once and I'll approve the PR.

2017-03-02 09:21 UTC, mayankamencherla commented on app/payments/razorpay.php
>  include_once ('razorpay/razorpay_common.inc');
Line break

2017-03-02 09:51 UTC, riagarg5 commented on app/payments/razorpay.php
>  include_once ('razorpay/razorpay_common.inc');
done

2017-03-02 09:52 UTC, mayankamencherla approved these changes

2017-03-02 10:21 UTC, 73sl4 commented on app/payments/RazorpayPayment.php
> +        if ((empty($razorpaySignature) == false) and (empty($razorpayPaymentId) == false))
strict comparison.

2017-03-02 10:59 UTC, captn3m0 requested changes

2017-03-02 10:59 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +            $_SESSION[$key] = $value;
opencart recommends using $this->session instead: https://stackoverflow.com/questions/8472027/session-variables-in-opencart

2017-03-02 10:59 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +            'receipt' => $orderId,
nit: align =>

2017-03-02 10:59 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +            setTimeout(function(){ razorpaySubmit(); }, 500);
Explain this please? setInterval to check whether window['Razorpay'] is defined and then a setTimeout for when it is?

Can we not use document.onload or some other event instead? /cc @razorpay/frontend

2017-03-02 10:59 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +        $razorpaySignature = $_POST['razorpay_signature'];
Put isset checks as well? This will cause issues if the form submission breaks by any reason

2017-03-02 10:59 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +                    $success = $api->utility->verifyPaymentSignature($attributes);
No need for a try-catch here. verifyPaymentSignature doesn't raise any exceptions.

2017-03-02 10:59 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +                $success = false;
Drop `success` variable here, and directly use the signature check instead

2017-03-02 10:59 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +       $html = <<<EOT
Can you add screenshot/GIF of how this looks?

2017-03-02 10:59 UTC, captn3m0 commented on app/payments/razorpay.php
> +        'name'        => Registry::get('settings.Company.company_name'),
space around periods.

2017-03-02 11:48 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +            $_SESSION[$key] = $value;
My bad. Too many *-cart

2017-03-02 11:53 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                    $success = $api->utility->verifyPaymentSignature($attributes);
It does. It throws Errors/BadRequest if the signature doesn't match

2017-03-02 11:54 UTC, riagarg5 commented
<img width="951" alt="screen shot 2017-03-02 at 5 23 51 pm" src="https://cloud.githubusercontent.com/assets/13147520/23506207/10022c1c-ff6d-11e6-857e-4ff8ff7bc2dd.png">

2017-03-02 11:54 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +       $html = <<<EOT
done

2017-03-02 11:55 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +            $_SESSION[$key] = $value;
cscart uses $_SESSION , it doesnt have $this->session

2017-03-02 12:13 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +                    $success = $api->utility->verifyPaymentSignature($attributes);
:( It shouldn't.

Filed https://github.com/razorpay/razorpay-php/pull/27

2017-03-02 12:33 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                    $success = $api->utility->verifyPaymentSignature($attributes);
ok :P

2017-03-02 12:35 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +                $success = false;
we can't do that. This is the case in case form submission breaks

2017-03-02 12:59 UTC, riagarg5 commented on app/payments/razorpay.php
> +        'name'        => Registry::get('settings.Company.company_name'),
done

2017-03-02 13:00 UTC, mayankamencherla requested changes

2017-03-02 13:00 UTC, mayankamencherla commented on app/payments/razorpay.php
> +    $razorpayOrder = $api->order->create($data);
Add a try catch around this line and echo the exception. 

echo 'CS Cart Error : ' . $e->getMessage();

2017-03-02 13:26 UTC, riagarg5 commented on app/payments/razorpay.php
> +    $razorpayOrder = $api->order->create($data);
done

2017-03-02 13:26 UTC, riagarg5 commented on app/payments/RazorpayPayment.php
> +            setTimeout(function(){ razorpaySubmit(); }, 500);
i put window.load

2017-03-02 13:54 UTC, mayankamencherla commented on app/payments/RazorpayPayment.php
> +                $success = $api->utility->verifyPaymentSignature($attributes);
Good.

2017-03-02 13:55 UTC, mayankamencherla approved these changes
@riagarg5 Nice work. @captn3m0 Kindly leave your final comments.

2017-03-06 11:03 UTC, captn3m0 requested changes

2017-03-06 11:03 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +       location.href = "http://localhost/cscart/index.php?dispatch=checkout.process_payment&clicked=true";
localhost url, needs fixing.

2017-03-06 11:03 UTC, captn3m0 commented on app/payments/razorpay.php
> +    if ((defined('IFRAME_MODE') === true) and (empty($_GET['clicked']) === true))
Leave a comment here stating why we are doing this

2017-03-06 11:03 UTC, captn3m0 commented on app/payments/RazorpayPayment.php
> +                $success = $api->utility->verifyPaymentSignature($attributes);
This will need change again, and a corresponding SDK update

2017-03-07 08:57 UTC, captn3m0 approved these changes

2017-03-07 09:14 UTC, merged